name: Big Bad Title

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    

jobs:
    First_thing_that_goes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Here runs the Meow command
              run: echo "Meow"
              shell: bash
              
    Serious_job:
        runs-on: ubuntu-latest
        steps:
            - name: Here runs the Goodbye command. Get ready
              run: echo "Goodbye"
              shell: bash
